issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - linters: [errcheck]
      text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
linters:
  disable-all: true
  enable:
    - nakedret
    - interfacer
    - varcheck
    - deadcode
    - structcheck
    - misspell
    - maligned
    - ineffassign
    - goconst
    - goimports
    - errcheck
    - unparam
    - golint
    - staticcheck
    - gosimple
    - unused
    - govet
    - typecheck
    - gocyclo
    - gofmt
    - dupl

run:
  deadline: 5m
